version: '3'

services:
    mysql:
        build: ${RELATIVE_PATH}/containers/mysql
        restart: always
        volumes:
            - ${RELATIVE_PATH}/containers/mysql:/etc/mysql/conf.d
            - ${RELATIVE_PATH}/containers_data/mysql_8-0-21:/var/lib/mysql
            - ${RELATIVE_PATH}/containers_logs/mysql_8-0-21:/var/log/mysql
            - ${RELATIVE_PATH}/containers_backups/mysql:/backups
            - ${RELATIVE_PATH}/containers_shared:/share
        env_file:
            - env.config
        expose:
            - "3306"
    golang:
        build: ${RELATIVE_PATH}/containers/golang
        restart: always
        security_opt:
            - seccomp:${RELATIVE_PATH}/containers/golang/seccomp.json
        cap_add:
            - SYS_BOOT
        volumes:
            - ${RELATIVE_PATH}/containers_logs/golang:/logs
            - ${RELATIVE_PATH}/containers_data:/data
            - ${RELATIVE_PATH}/containers_backups/mysql:/backups-sql
            - ${RELATIVE_PATH}/containers_data/golang/certificates:/certificates
            - "/etc/localtime:/etc/localtime:ro"  # linux only
            - "/etc/timezone:/etc/timezone:ro"    # linux only
        env_file:
            - env.config
        environment:
            - URL_SCHEME=${URL_SCHEME}
            - DEBUG=${DEBUG}
        links:
            - mysql
        depends_on:
            - mysql
        expose:
            - "80"
            - "443"
        ports:
            - "${LOCAL_IP}:80:80"
            - "${LOCAL_IP}:443:443"
